all: address-3 address-5 addressArray-5

address-3: address-3.c
	gcc -o address-3 address-3.c

address-5: address-5.c
	gcc -o address-5 address-5.c

addressArray-5: addressArray-5.c
	gcc -o addressArray-5 addressArray-5.c

clean:
	rm address-3 address-5 addressArray-5
